Theory Questions

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Purpose of NumPy in Scientific Computing and Data Analysis: NumPy (Numerical Python) is a fundamental package for scientific computing and data analysis in Python. Its primary purpose is to enable efficient numerical operations on large, multi-dimensional arrays and matrices. NumPy provides tools for performing mathematical, logical, and statistical operations on arrays, offering significant performance improvements over standard Python data structures like lists. This makes it invaluable for tasks such as numerical analysis, data processing, and machine learning.

Advantages of NumPy: Efficient Memory Usage: NumPy arrays (ndarrays) use less memory compared to Python lists. They store data in contiguous blocks of memory, which enhances performance, especially for large datasets.

Vectorized Operations: NumPy supports vectorized operations, allowing mathematical computations to be performed on entire arrays without the need for explicit loops. This leads to much faster execution times compared to traditional Python loops.

Multi-dimensional Arrays: NumPy provides support for n-dimensional arrays, which can be used for handling complex data structures like matrices and tensors. This is useful in areas like image processing and machine learning.

Broad Range of Functions: NumPy includes a comprehensive set of mathematical functions (e.g., trigonometric, algebraic, statistical) that operate on arrays, making it suitable for complex numerical computations.

How NumPy Enhances Python’s Numerical Capabilities: Faster Computation: NumPy uses optimized C code under the hood, which allows for faster execution of numerical computations than using native Python loops.

Advanced Indexing and Slicing: It allows for advanced array indexing, slicing, and reshaping, which makes data manipulation more intuitive and efficient.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

np.mean() Definition: np.mean() calculates the arithmetic mean (simple average) of the elements in an array along the specified axis or of all elements if no axis is provided. Usage: The arithmetic mean is calculated by summing all the values in the array and dividing by the total number of elements. It treats all elements equally and doesn’t consider weights.

When to Use: Use np.mean() when you want to calculate a simple, unweighted average of an array’s values. It is straightforward and quick when weights are not involved.

np.average() Definition: np.average() computes the weighted average of the elements in an array. You can optionally provide weights to influence the contribution of each element to the average. Usage: If weights are provided, the function calculates a weighted average, where each element in the array contributes to the mean according to its corresponding weight. If no weights are provided, np.average() behaves similarly to np.mean() and computes the simple arithmetic mean.
When to Use: Use np.average() when you need to calculate a weighted mean, where certain elements should have a larger or smaller influence on the average. If no weights are provided, it can still be used as a substitute for np.mean().

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Reversing a NumPy array along different axes can be useful in many scenarios, such as manipulating data or performing operations where order matters. NumPy offers several ways to reverse arrays, and the method you use depends on the dimensionality of the array (1D, 2D, etc.) and which axis you want to reverse.-1]

In [78]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse using slicing
reversed_arr = arr_1d[::-1]


In [80]:
# 2D array (matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse row
reversed_rows = arr_2d[::-1, :]

# Reverse columns
reversed_cols = arr_2d[:, ::-1]

# Reverse both rows and columns
reversed_both = arr_2d[::-1, ::-1]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Determining the Data Type of Elements in a NumPy Array In NumPy, you can easily determine the data type of elements in an array using the dtype attribute. This attribute provides information about the type of data stored in the array (e.g., integers, floats, strings, etc.). Here's how you can determine the data type:

Importance of Data Types in NumPy for Memory Management and Performance Data types play a critical role in memory management and performance in NumPy. Choosing the correct data type allows you to optimize both memory usage and computational efficiency.

Memory Management Efficient Memory Usage:
NumPy arrays are homogeneous, meaning all elements in an array must have the same data type. This allows NumPy to store data in a contiguous block of memory, leading to efficient memory usage and faster access times. For example, an array of int8 (8-bit integers) takes significantly less memory than an array of int64 (64-bit integers). Choosing the right data type based on the expected range of values is crucial for managing memory in large datasets.

In [84]:
arr_int8 = np.array([1, 2, 3, 4], dtype=np.int8)
arr_int64 = np.array([1, 2, 3, 4], dtype=np.int64)
print(arr_int8.nbytes)
print(arr_int64.nbytes)


4
32


Memory Overhead:

Choosing a data type with unnecessarily large precision can result in wasted memory. For instance, if you know your data consists of small integers, using a 64-bit float would be inefficient and consume more memory than necessary.

Performance Faster Computation:
NumPy operations are heavily optimized for specific data types, allowing for fast computations when working with arrays. When the correct data type is used, NumPy can leverage vectorized operations and low-level libraries (like BLAS and LAPACK) to accelerate performance.

Numerical Precision:

Data types directly impact the precision and accuracy of numerical computations. For example, using float32 for large datasets may lead to precision loss in very large numbers or small decimal differences. In contrast, float64 provides higher precision but requires more memory and processing power



5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

What are ndarrays in NumPy? An ndarray (N-dimensional array) is the central data structure of NumPy. It represents a homogeneous, multidimensional array of fixed-size items. Each element in the array is of the same type, and the number of dimensions (or axes) is known as the array's rank. These arrays allow efficient storage and manipulation of large datasets, and they are highly optimized for performance in numerical computations.

Key Features of ndarrays Homogeneity:

All elements in a NumPy ndarray must be of the same data type (e.g., all integers, floats, etc.). This allows for better memory management and faster operations compared to Python lists, which can store elements of different types. Fixed Size:

Once created, the size (number of elements) of an ndarray is fixed. You can’t change its size after the array is created, although you can reshape it (change its structure without changing the total number of elements). Multidimensional:

An ndarray can have multiple dimensions (2D, 3D, etc.), unlike Python lists, which are primarily 1D but can be nested to simulate multidimensionality. In NumPy, you can efficiently work with arrays of any dimension. Efficient Memory Management:

ndarrays are stored in a contiguous block of memory, which allows for fast access and better cache utilization. This is much more efficient than Python lists, where elements can be scattered across different memory locations.

In [91]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2


Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array along the appropriate dimension. This makes many mathematical operations more flexible and efficient. Slicing and Indexing:

ndarrays support advanced slicing and indexing, including multi-dimensional slicing and boolean indexing, which makes accessing specific parts of the array efficient.

How ndarrays Differ from Python Lists Feature ndarrays (NumPy Arrays) Python Lists Homogeneity Elements must be of the same type Can store elements of different data types Fixed Size Size is fixed; cannot append or remove elements Dynamic size; can append, remove, or modify Memory Storage Stored in contiguous blocks of memory (compact) Elements can be scattered in memory Performance Faster due to vectorized operations and low-level optimizations Slower, especially for large datasets or loops Broadcasting Supports broadcasting (operations on arrays of different shapes) No support for broadcasting Slicing More powerful slicing and indexing, supports multidimensional Limited slicing capabilities, no multi-dimensional slicing

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Memory Efficiency Homogeneous Data: NumPy arrays store elements of a single data type, allowing them to be more compact and efficient in memory compared to Python lists, which can store elements of different types. This homogeneity allows NumPy arrays to be stored in contiguous blocks of memory. Fixed Size: NumPy arrays have a fixed size, which reduces overhead because memory is allocated once when the array is created. In contrast, Python lists are dynamic and need to resize their underlying data structure as elements are added, which involves costly memory reallocation

In [96]:
import numpy as np
import sys

# Create a NumPy array and a Python list
arr = np.arange(1000)
lst = list(range(1000))

# Memory usage comparison
print(arr.nbytes)  # NumPy array memory: 8000 bytes
print(sys.getsizeof(lst))  # Python list memory: ~9000+ bytes (depends on system)


4000
8056


Vectorized Operations (No Loops Needed) NumPy provides vectorized operations, meaning operations are performed element-wise across entire arrays without the need for explicit loops. This is a key feature of NumPy that contributes to its high performance.

In [99]:
import numpy as np
import time

# Create a large array
arr = np.arange(1000000)
lst = list(range(1000000))

# NumPy array multiplication (vectorized)
start_time = time.time()
arr_result = arr * 2
print("NumPy time:", time.time() - start_time)  # Very fast

# Python list multiplication (with a loop)
start_time = time.time()
lst_result = [x * 2 for x in lst]
print("List time:", time.time() - start_time)  # Much slower


NumPy time: 0.0010027885437011719
List time: 0.053385019302368164


Low-level Optimization and Use of C/Fortran Libraries Low-level implementation: NumPy is implemented in C and Fortran, which are compiled languages known for their speed. When operations are performed on NumPy arrays, they call these underlying libraries, bypassing the overhead of Python’s interpreted execution. BLAS and LAPACK integration: NumPy uses highly optimized libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) for numerical computations, further enhancing performance in tasks like matrix operations, linear algebra, and FFTs.


Broadcasting for Efficient Computation Broadcasting: NumPy’s broadcasting mechanism allows arrays of different shapes to be combined in element-wise operations without creating copies or using loops. This leads to both memory and computational efficiency.

Performance Benefits: Memory Efficiency: NumPy arrays are more memory-efficient than Python lists due to homogeneous data and fixed sizes. Vectorized Operations: NumPy allows for fast, vectorized operations without the need for explicit loops. Low-level Optimizations: NumPy uses optimized C, BLAS, and LAPACK libraries, enabling high-speed computations. Contiguous Memory and Cache Optimization: NumPy arrays use contiguous memory blocks, improving cache performance. Broadcasting: Efficient handling of arrays with different shapes, reducing the need for complex loops. Slicing and In-place Operations: Fast slicing and in-place operations, minimizing memory and performance overhead.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

np.vstack() (Vertical Stack) Purpose: Stacks arrays vertically (row-wise). Axis of Concatenation: It stacks arrays along the first axis (axis=0). Shape Requirements: The input arrays must have the same number of columns (or same shape along the second axis)

np.hstack() (Horizontal Stack) Purpose: Stacks arrays horizontally (column-wise). Axis of Concatenation: It stacks arrays along the second axis (axis=1). Shape Requirements: The input arrays must have the same number of rows (or same shape along the first axis)

Usage and Outputs:- vstack() is used when you want to stack arrays vertically, increasing the number of rows in the resulting array. hstack() is used when you want to stack arrays horizontally, increasing the number of columns in the resulting array.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

np.fliplr() (Flip Left to Right) Purpose: fliplr() reverses the columns of a 2D array, effectively flipping it horizontally (left to right). Dimensional Requirement: The input array must be at least 2D. It flips along the second axis (axis=1). Effect: The elements in each row are reversed, while the rows themselves remain in the same order

np.flipud() (Flip Up to Down) Purpose: flipud() reverses the rows of a 2D array, effectively flipping it vertically (up to down). Dimensional Requirement: flipud() works on arrays of any dimension (1D, 2D, etc.). It flips along the first axis (axis=0). Effect: The rows of the array are reversed, while the columns remain in the same order.

ffects on Higher-Dimensional Arrays For arrays with more than 2 dimensions, both fliplr() and flipud() work on specific axes.

fliplr(): Works on the second axis (axis=1), so it will reverse the columns of 2D slices along other dimensions. flipud(): Works on the first axis (axis=0), so it will reverse the rows of 2D slices along other dimensions

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the split() method, which requires the input array to be evenly divisible by the number of splits, array_split() can handle uneven splits, making it more flexible

Key Features of array_split(): Input Array: It works with arrays of any dimensionality (1D, 2D, 3D, etc.). Number of Splits: You can specify the number of sub-arrays you want to create.

Handling Uneven Splits: When the number of elements in the array is not evenly divisible by the number of splits, array_split() distributes the extra elements to the earlier sub-arrays. The sub-arrays are created such that their sizes differ by at most 1 element.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization: Definition: Vectorization in NumPy refers to the process of applying operations directly to entire arrays (or vectors) without using explicit Python loops. Instead of iterating over individual elements one-by-one, NumPy allows element-wise operations to be performed on the entire array simultaneously. Why It’s Efficient: NumPy operations are implemented in C, which means they bypass the performance limitations of Python loops

In [115]:
import numpy as np

# Two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Vectorized addition (element-wise)
result = arr1 + arr2
print(result)


[ 6  8 10 12]


Advantages of Vectorization: Performance: Since NumPy performs operations at the lower-level C language, vectorized operations are much faster than pure Python loops. Readability: The code is cleaner and more concise, avoiding complex loops.

Broadcasting: Definition: Broadcasting is a mechanism in NumPy that allows operations on arrays of different shapes. Instead of requiring arrays to have identical shapes for element-wise operations, NumPy automatically "broadcasts" smaller arrays across the larger array so that the shapes match. How It Works: When performing operations on arrays of different shapes, NumPy stretches (or broadcasts) the smaller array along a dimension to match the shape of the larger array, as long as they follow certain broadcasting rules.

Practical Questions

1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [8]:
import numpy as np
a = np.array([[1,2,3] ,[4,5,6] ,[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#exchange rows and columns
tran = a.T
print(tran)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
# reshape into 2X5
arr = arr.reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
# reshape into 5X2
arr = arr.reshape(5,2)
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3) Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [36]:
arr = np.random.rand(4,4)
arr1 = np.zeros((6,6))
arr1[1:5,1:5]=arr
print(arr1)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06527641 0.63383891 0.13059403 0.53678355 0.        ]
 [0.         0.60250636 0.62275646 0.24258798 0.80099218 0.        ]
 [0.         0.86296267 0.41450776 0.93894008 0.43830367 0.        ]
 [0.         0.65133049 0.75902917 0.8676112  0.20764711 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [41]:
import numpy as np


array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [44]:
import numpy as np


string_array = np.array(['python', 'numpy', 'pandas'])

uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)
capitalize_array = np.char.capitalize(string_array)
print("Original array:", string_array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)
print("Capitalize:", capitalize_array)


Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


6) Generate a NumPy array of words. Insert a space between each character of every word in the array 

In [47]:
import numpy as np


words_array = np.array(['hello', 'world', 'numpy', 'python'])

spaced_array = np.char.join(' ', words_array)

print("Original array:", words_array)
print("Spaced array:", spaced_array)

Original array: ['hello' 'world' 'numpy' 'python']
Spaced array: ['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [50]:
import numpy as np

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [53]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [56]:
import numpy as np


random_integers = np.random.randint(0, 1001, size=100)


def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


prime_numbers = [num for num in random_integers if is_prime(num)]


print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [766 408 681 652 868 570 711 670 249 754 920 257 241 438 972 604 190  91
 683 828  25 730 579 599 823 234 111 697 145  30 636 104 848 672 669 927
 600 322 751 208 208 466 438 197  63 776 524 547  97 622 752 883 308 598
 603 473 722 260 395 779 275 628 987 424 246 928 865 694 381 936 631 728
 365 648 396 236 115 830  74 261 284 982 871 424  36 351 729 446 700 217
 580 619 136 167 673 929 639 786 158 765]
Prime Numbers: [257, 241, 683, 599, 823, 751, 197, 547, 97, 883, 631, 619, 167, 673, 929]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [63]:
import numpy as np

daily_temperatures = np.random.randint(-10, 41, size=30)


weekly_temperatures = daily_temperatures.reshape(3, -1)


weekly_averages = np.mean(weekly_temperatures, axis=1)


print("Daily Temperatures for a Month:\n", daily_temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for a Month:
 [36 38  0 33  3 13 31  4 -6 -4 15 23 -4  3 34  2 19 -3 -2 18  7 36 29 18
 17 29 11 -1 12 35]
Weekly Temperatures:
 [[36 38  0 33  3 13 31  4 -6 -4]
 [15 23 -4  3 34  2 19 -3 -2 18]
 [ 7 36 29 18 17 29 11 -1 12 35]]
Weekly Averages: [14.8 10.5 19.3]
